### ISSUE TITLE
Research on mobile deep linking 

### ISSUE THREAD

**Issue by jyaneshseeam** [UPEI-Android/group-project-mindjogg#108]
## Context

To accompany the authentication system, links from email must trigger open the app directly 

## Problem
Mobile deep linking is one of the options, but more research is needed before using it

## Solution
- [ ] Research on mobile deep linking fo react native
- [ ] Describe your choice to the group

**Comment by ja-chisholm** [comment]
Deep linking can be done with the react navigation library we are already using: https://reactnavigation.org/docs/2.x/deep-linking/

Basically, links can be registered on the app as they would be for a web app, and then when clicked, will open a specific page through navigation. We do need to register a URI prefix, but that wouldn't be too difficult.

@sontushkpaul @DemiAdisa @jyaneshseeam what do you guys think? If you want to find another library for deep linking, react navigation would still be compatible with it because it lets you disable the deep linking that it provides
