### ISSUE TITLE
Create password box component

### ISSUE THREAD

**Issue by ja-chisholm** [UPEI-Android/group-project-mindjogg#81]
## Context
We will need a password component. It should extend textbox, and add hiding/showing the input and make sure whatever input it passes on is encrypted

## Problem
We must make this password component.

## Solution
- [ ] Determine how to implement this component
- [ ] Implement it, making sure that it can be used anywhere a textbox can be used
- [ ] Complete issue #82 for testing

**Comment by sontushkpaul** [comment]
@ja-chisholm  Please prioritize the implementation of the text box and password box components because it is the building block of other screens and components. The issue is blocking https://github.com/UPEI-Android/group-project-mindjogg/issues/49 and https://github.com/UPEI-Android/group-project-mindjogg/issues/54
